In [7]:
import torch

# Create a 1D tensor (vector)
x = torch.tensor([1, 2, 3, 4])
print("1D Tensor:", x)

# Create a 2D tensor (matrix)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("2D Tensor:\n", matrix)

# Check shape
print("Shape of matrix:", matrix.shape)

# Create tensor with zeros or ones
zeros = torch.zeros(3, 3)
ones = torch.ones(2, 4)
print("Zeros:\n", zeros)
print("Ones:\n", ones)


1D Tensor: tensor([1, 2, 3, 4])
2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of matrix: torch.Size([2, 3])
Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Addition
print("Add:", a + b)

# Element-wise multiplication
print("Multiply:", a * b)

# Matrix multiplication
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
print("Matrix multiply:\n", torch.matmul(mat1, mat2))

# Mean and sum
print("Mean:", a.float().mean())
print("Sum:", a.sum())


Add: tensor([5, 7, 9])
Multiply: tensor([ 4, 10, 18])
Matrix multiply:
 tensor([[19, 22],
        [43, 50]])
Mean: tensor(2.)
Sum: tensor(6)


In [9]:
# Reshape tensor
x = torch.arange(12)  # [0, 1, 2, ..., 11]
print("Original:", x)

reshaped = x.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Indexing and slicing
print("First row:", reshaped[0])
print("First two columns:\n", reshaped[:, :2])


Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
First row: tensor([0, 1, 2, 3])
First two columns:
 tensor([[0, 1],
        [4, 5],
        [8, 9]])


In [10]:
x = torch.tensor([2.0, 3.0], requires_grad=True)  # track gradients

y = x ** 2 + 3 * x + 1  # some function

print("y:", y)

# Compute gradients (dy/dx)
y.sum().backward()

print("Gradients:", x.grad)  # dy/dx at x


y: tensor([11., 19.], grad_fn=<AddBackward0>)
Gradients: tensor([7., 9.])


In [24]:
import torch.nn as nn

# Define a simple linear layer
linear = nn.Linear(in_features=3, out_features=2)

# Example input: batch of 1, 3 features
input = torch.randn(1, 3)

# Forward pass
output = linear(input)
print("Output:", output)


Output: tensor([[1.0894, 0.0622]], grad_fn=<AddmmBackward0>)


In [14]:
import torch.optim as optim

model = nn.Linear(2, 1)
optimizer = optim.SGD(model.parameters(), lr=0.000001)

# Dummy input and target
input = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])

# Forward
output = model(input)

# Loss (MSE)
loss = (output - target).pow(2).mean()
print("Loss:", loss.item())

# Backward pass
loss.backward()

# Update weights
optimizer.step()

# Zero gradients before next pass
optimizer.zero_grad()


Loss: 6.133118629455566
